FROM fedora:35

LABEL maintainer.name="ROOT team"
LABEL maintainer.email="root-dev@cern.ch"

COPY library-scripts/packages-fedora packages

COPY library-scripts/*.sh /tmp/library-scripts/
COPY library-scripts/scl_enable /opt/app-root/etc/

RUN dnf update -q -y \
    && dnf install -y $(cat packages) \
    && localedef -i en_US -f UTF-8 en_US.UTF-8 \
    && rm -f /packages \
    && dnf clean all

RUN bash /tmp/library-scripts/provide-cmake.sh \
    && bash /tmp/library-scripts/provide-libssh2.sh \
    && bash /tmp/library-scripts/provide-boost.sh \
    && bash /tmp/library-scripts/provide-cppzmq.sh \
    && rm -rf /tmp/library-scripts

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

COPY library-scripts/*.sh /tmp/library-scripts/

RUN bash /tmp/library-scripts/provide-user.sh ${USERNAME} ${USER_UID} ${USER_GID}